# Generated by Django 6.0.3 on 2026-03-24 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='markdown_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
